apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: user-test
spec:
  passwordSecretKeyRef:
    name: user-dev-password
    # Match to metadata.name of the User Secret
    key: password
  username: "user-1"
  db: "admin" #
  mongodbResourceRef:
    name: "payment-dev"
    # Match to MongoDB resource using authenticaiton
  roles:
  - db: "admin"
    name: "clusterAdmin"
  - db: "admin"
    name: "userAdminAnyDatabase"
  - db: "admin"
    name: "readWriteAnyDatabase"
  - db: "admin"
    name: "userAdminAnyDatabase"