apiVersion: v1
kind: Secret
metadata:
  name: openshift-pull-secret
stringData:
  .dockerconfigjson: |
      {
        "auths": {
          "registry.redhat.io": {
            "auth": "AUTH"
          },
          "registry.connect.redhat.com": {
            "auth": "AUTH"
          }
        }
      }
      
type: kubernetes.io/dockerconfigjson
