apiVersion: v1
stringData:
  FirstName: Admin
  LastName: User
  Password: <<Password>>
  Username: <<UserName>>
kind: Secret
metadata:
  name: ops-manager-admin-secret
  namespace: mongodb
type: Opaque
