apiVersion: v1
stringData:
  FirstName: Admin
  LastName: User
  Password: p1m0ngo-@dm1n
  Username: pimongo-admin
kind: Secret
metadata:
  name: ops-manager-admin-secret
  namespace: mongodb
type: Opaque
