apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: test-mongodb-cluster
  namespace: mongodb
spec:
  members: 3
  version: 4.4.4-ent
  type: ReplicaSet
  authentication:
    enabled: true
    modes: 
     - "SCRAM"
  opsManager:
    configMapRef:
      name: ops-manager-configmap-2
  credentials: ops-manager-admin-key
  persistent: true
  podSpec:
    persistence:
      single:
        storage: 16Gi
        storageClass: gp2
  # podSpec:
  #   podTemplate:
  #     spec:
  #       containers:
  #       - name: mongodb-enterprise-database
  #         resources:
  #           limits:
  #             cpu: 2
  #             memory: 1.5G
  #           requests:
  #             cpu: 1
  #             memory: 1G
  #           persistence:
  #             single:
  #               storage: 16Gi