apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: demo-mongodb-cluster
  namespace: mongodb
spec:
  members: 3
  version: 4.4.4-ent
  type: ReplicaSet
  # security:
  #   authentication:
  #     enabled: true
  #     modes: ["SHA", "SCRAM"]
  opsManager:
    configMapRef:
      name: ops-manager-configmap
  credentials: ops-manager-admin-key
  persistent: true