# Default values for mongo-kubernetes-operator-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: finnova-ops-manager

openshift:
  imagePullSecret: openshift-pull-secret
  registry:
    auth: "MTU3OTU1NDR8cGltb25nby1zZXJ2aWNlOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKak0yRTBOalF4WkRrMU1UTTBOamd6WWpaaU9EQXlNMlZqT0RVM1ltRmpaQ0o5LkhpZ2szQ1ZnNzNmTHZyX1ZzenhTUm9nVW51OWs1Q1lJbHQ5SDNKLTZzcmJkeTBSX1VEc2tFdmpyZm5BZVhoNER2b2Vxb0RzMTNlZDN0NWlmZTNyLVhKZ1B0Xzg0dWItb1B2SDRMMXBqS3VEeVFxRk1tMHJSVmd4b25hY1VPZ09GUzZSWl9CMmMwRzdPTl9jbHoyTHBoNEQyQUNCck9CWjVwWmNURVVUUk5fejZ2ZjdMV01kRmVYYWNKS3FBOVk3YUF0cW16cG1BZ3RlOVpkWjdWdjhGZ1cwMjRQOWpsc1FISk9MbW44ZnBxamVFX3I5azJVNzBKa01FV292dUpWa3k1UlZvUXQ0VnNzZW1GLTFUN3UzRVVwY0lyT3R5bFdVcm5qU2trLTN1Q2k3UUhtaDkxZGZQSkhoU3F3MlZpV29qcWtBSUpzdHJjMGwzSGdnQ3N3UElfTnAxVFBVdGo0TF9JSUNPV1E5QnR4Mlh0WkI0Y0JOSFVXdkNvZXU5bmsxRTlOdlQtQi1PUWNoTi0wdXIxbkxVTmd2UnJOUFJfYXpCcGh2TDRkODZmSE5mdXVZZ0tXWmFMUlJCS2lrUVJaNnVEdEtORWNLeHdjMmFuMkxDM2cyS0t5S20zNVFLeUhFZUcyYmE5Vy1SaktJT2lRVUtsci0wNnUzcF90LWZoQXMxLVIxTGdjOFA4X1VBRzJiWWV0Wmlta1Y3R04tM2FQSlpEYTJhbkN0WnVNSmdZbFFyNC1XWWRtVWtNcFE1XzM3OXZMX1p1LXdTLXFYQVYtY0hjMUl5eWdDdlhBOEZoelZDQm5wMjNHVjc1Z2lZbUk5eGl4NVBtT0YybmNzUGFnMzk1S2dvVXo2bjA0c1VsTmFpSy1qbHI3OU5vX20ySlp3Z052SDZqVWhMaDFF"

opsmanager:
  name: finnova-ops-manager
  adminCredentials: ops-manager-admin-secret
  replicas: 1
  version: 4.4.4
  appdb:
    version: 4.4.4-ent
    storage: 16Gi
    storageClass: gp2
  secret:
    name: ops-manager-admin-secret
  externalConnectivity:
    type: LoadBalancer
  backup:
    name: mongodb-bkp-cluster
    enabled: false
    oplogs:
      name: oplog1
  admin:
    username: pimongo-admin
    password: p1m0ngo-@dm1n

backup:
  enabled: false
  blockStores:
  oplogs:

configuration: 
  mms.ignoreInitialUiSetup: "true"
  mms.fromEmailAddr: "jane.doe@example.com"
  mms.replyToEmailAddr: "jane.doe@example.com"
  mms.adminEmailAddr: "jane.doe@example.com"
  mms.mail.transport: "smtp"
  mms.mail.hostname: "example.com"
  mms.mail.port: "25"

