apiVersion: v1
stringData:
  FirstName: Admin
  LastName: User
  Password: "{{.Values.opsmanager.admin.password}}"
  Username: "{{.Values.opsmanager.admin.username}}"
kind: Secret
metadata:
  name: "{{ .Values.opsmanager.secret.name }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.openshift.imagePullSecret }}"
  namespace: "{{ .Values.namespace }}"
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.redhat.io": {
          "auth": "{{ .Values.openshift.registry.auth }}"
        },
        "registry.connect.redhat.com": {
          "auth": "{{ .Values.openshift.registry.auth }}"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
