# Default values for mongocluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

password:
  name: user-dev-password
  value: Passw0rd-1

user:
  name: user-dev

mongocluster:
  name: mongodb-cluster-dev
  version: 4.4.4-ent
  members: 3
  storageclass: gp2
  storage: 16Gi

opsmanager:
  secret:
    name: ops-manager-api-key
    privateKey: "4c399a66-08e0-41bd-9c5d-2709eab8037c"
    publicKey: "PJYTCLRD"
  configMap:
    name: ops-manager-configmap
  baseUrl: "http://finnova-ops-manager-svc.mongodb.svc.cluster.local:8080"
  orgId: "6216e32e33d04a3eb5f92141"

namespace: mongodb-dev