# Default values for mongocluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

password:
  name: user-dev-password
  value: Passw0rd-1

user:
  name: user-dev

mongocluster:
  name: mongodb-cluster-dev
  version: 4.4.4-ent
  members: 3
  storageclass: gp2
  storage: 16Gi

opsmanager:
  secret:
    name: ops-manager-api-key
    privateKey: "7b37c9ba-e1eb-4fb5-8a75-f2b4316116b9"
    publicKey: "YZIESKIH"
  configMap:
    name: ops-manager-configmap
  baseUrl: "http://finnova-ops-manager-svc.mongodb.svc.cluster.local:8080"
  orgId: "621701ff6433037e690c6015"

namespace: mongodb-dev