# Default values for mongocluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

password:
  name: user-dev-password
  value: Passw0rd-1

user:
  name: user-dev

mongocluster:
  name: payment-dev
  version: 4.4.4-ent
  members: 3
  storageclass: gp2
  storage: 16Gi

opsmanager:
  secret:
    name: ops-manager-api-key
    privateKey: "7c2e565a-ea23-41d9-9043-1855935923d9"
    publicKey: "QRUZEXPW"
  configMap:
    name: ops-manager-configmap
  baseUrl: "http://finnova-ops-manager-svc.finnova-ops-manager.svc.cluster.local:8080"
  orgId: "62170d239121f020bd55f344"

namespace: finnova-dev