apiVersion: v1
stringData:
  user: "{{ .Values.opsmanager.secret.user }}"
  publicApiKey: "{{ .Values.opsmanager.secret.publicApiKey }}"
kind: Secret
metadata:
  name: "{{ .Values.opsmanager.secret.name }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
---
apiVersion: v1
data:
  baseUrl: "{{ .Values.opsmanager.baseUrl }}"
  orgId: "{{ .Values.opsmanager.orgId }}"
kind: ConfigMap
metadata:
  name: "{{ .Values.opsmanager.configMap.name }}"
  namespace: "{{ .Values.namespace }}"
