apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.password.name }}"
  namespace: "{{ .Values.namespace }}"
  # corresponds to user.spec.passwordSecretKeyRef.name
type: Opaque
stringData:
  password: "{{ .Values.password.value }}"
  # corresponds to user.spec.passwordSecretKeyRef.key
