apiVersion: v1
stringData:
  FirstName: Admin
  LastName: User
  Password: "{{.Values.opsmanager.admin.password}}"
  Username: "{{.Values.opsmanager.admin.username}}"
kind: Secret
metadata:
  name: "{{ .Values.opsmanager.secret.name }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
